{
 "title": "Linux Machine Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Machine",
    "label": "Machine",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Status | $Machine",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$Machine\"} ",
     "legendFormat": "System Status"
    }
   ]
  },
  {
   "title": "System Uptime | $Machine",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=~\"$Machine\"} - node_boot_time_seconds{job=~\"$Machine\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "RAM | $Machine",
   "type": "stat",
   "description": "Total Amount of Memory",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$Machine\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU Cores | $Machine",
   "type": "stat",
   "description": "Total number of CPU cores.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"$Machine\"}) by (cpu))",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "Memory Usage (%) | $Machine",
   "type": "stat",
   "description": "Percentage of memory currently in use.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemFree_bytes{job=~\"$Machine\"} / node_memory_MemTotal_bytes{job=~\"$Machine\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Disk Usage (%) | $Machine",
   "type": "stat",
   "description": "Percentage of disk space currently in use.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum(node_filesystem_free_bytes{job=~\"$Machine\"}) / sum(node_filesystem_size_bytes{job=~\"$Machine\"}))",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Running Processes | $Machine",
   "type": "stat",
   "description": "Currently Running Processes.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_running{job=~\"$Machine\"}",
     "legendFormat": "Running Processes"
    }
   ]
  },
  {
   "title": "Total N/W Bytes Received (24h) | $Machine",
   "type": "stat",
   "description": "Total bytes received over the network by host in 24 hours.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=~\"$Machine\"}[24h]))"
    }
   ]
  },
  {
   "title": "Server Load Averages | $Machine",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "node_load1{job=\"$Machine\"}",
     "legendFormat": "Load (1m)"
    },
    {
     "expr": "node_load5{job=\"$Machine\"}",
     "legendFormat": "Load (5m)"
    },
    {
     "expr": "node_load15{job=\"$Machine\"}",
     "legendFormat": "Load (15m)"
    }
   ]
  },
  {
   "title": "Resource Wait Time Overview | $Machine",
   "type": "bargauge",
   "description": "CPU Wait Time: Measures the time processes spend waiting for CPU resources, indicating potential contention.\n\nMemory Wait Time: Tracks the time processes wait for memory availability, highlighting memory pressure.\n\nIO Wait Time: Reflects the time processes spend waiting for I/O operations to complete, indicating disk performance issues.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{job=\"$Machine\"}[$__rate_interval])",
     "legendFormat": "CPU Wait"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{job=\"$Machine\"}[$__rate_interval])",
     "legendFormat": "Memory Wait"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{job=\"$Machine\"}[$__rate_interval])",
     "legendFormat": "I/O Wait"
    }
   ]
  },
  {
   "title": "Blocked Processes | $Machine",
   "type": "stat",
   "description": "Currently Blocked Processes.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_blocked{job=~\"$Machine\"}",
     "legendFormat": "Running Processes"
    }
   ]
  },
  {
   "title": "Total N/W Bytes Transmitted Last (24h)",
   "type": "stat",
   "description": "\nTotal bytes transmitted over the network by host in 24 hours.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=~\"$Machine\"}[24h]))"
    }
   ]
  },
  {
   "title": "Disk Space Used | $Machine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$Machine\", device!~'rootfs|tmpfs|squashfs'} * 100) / node_filesystem_size_bytes{job=\"$Machine\", device!~'rootfs|tmpfs|squashfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk (Free) | $Machine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 9 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=~\"$Machine\",fstype!~\"(tmpfs|rootfs)\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Basic | $Machine",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$Machine\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$Machine\"} - node_memory_MemFree_bytes{job=\"$Machine\"} - (node_memory_Cached_bytes{job=\"$Machine\"} + node_memory_Buffers_bytes{job=\"$Machine\"} + node_memory_SReclaimable_bytes{job=\"$Machine\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"$Machine\"} + node_memory_Buffers_bytes{job=\"$Machine\"} + node_memory_SReclaimable_bytes{job=\"$Machine\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$Machine\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"$Machine\"} - node_memory_SwapFree_bytes{job=\"$Machine\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Activity | $Machine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 16 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"$Machine\"}[5m]) > 0",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "- irate(node_disk_written_bytes_total{job=~\"$Machine\"}[5m]) < 0",
     "legendFormat": "Write ({{device}})"
    }
   ]
  },
  {
   "title": "CPU Load | $Machine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{job=~\"$Machine\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk IO | $Machine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=~\"$Machine\"}[5m]) > 0",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "- irate(node_disk_write_time_seconds_total{job=~\"$Machine\"}[5m]) < 0",
     "legendFormat": "Write ({{device}})"
    }
   ]
  },
  {
   "title": "Disk (Free) | $Machine",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"(tmpfs|rootfs).*\",job=~\"$Machine\"}"
    }
   ]
  }
 ]
}